### ISSUE TITLE
Scientific notation in some export results

### ISSUE THREAD

**Issue by Kaputmaher** [micwalk/blender-export-diffusion#1]
In some export fragments there are numbers with an exponential notation. 
Example: `152:(-5.912394876466664e-05)`

**Comment by micwalk** [comment]
Does this cause an issue when parsing in a collab notebook? I've not noticed an error but it might be silently dropping frames.

**Comment by Kaputmaher** [comment]
Sorry, it's okay, it's a third-party tool did not understand the notation.
